Update backend-cd.yml

diff --git a/.github/workflows/backend-cd.yml b/.github/workflows/backend-cd.yml
--- a/.github/workflows/backend-cd.yml
+++ b/.github/workflows/backend-cd.yml
@@ -1,127 +1,174 @@
 name: Backend Continuous Deployment
-
 on:
   push:
     branches:
       - main
-    paths:
-      - 'starter/frontend/**'   
   workflow_dispatch:
-
 jobs:
-  lint:
-    name: Linter
+  backend-cd-lint:
+    name: backend-cd-lint
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: starter/backend
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Install pipenv and flake8
-        run: |
-          pip install --user pipenv flake8
-      
-      - name: Set up Python environment
-        run: |
-          pipenv install
-
-      - name: Run Linter
-        run: pipenv run lint
-
-      - name: Cache Dependencies
-        id: CachingData
-        uses: actions/cache@v3
+      - name: Checkout Code
+        uses: actions/checkout@v4
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v5
         with:
-          path: ~/.local/share/virtualenvs
-          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}
-    
-  test:
-    name: Test
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: starter/backend
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Install pipenv and flake8
+          python-version: '3.10'
+      - name: Install pipenv
         run: |
-          pip install --user pipenv flake8
-      
-      - name: Set up Python environment
-        run: |
-          pipenv install
-      
-      - name: Run linting
-        run: pipenv run lint
-
-      - name: Cache Python Dependencies
-        id: CachingData
-        uses: actions/cache@v3
+          python -m pip install --upgrade pip
+          pip install pipenv
+      - name: Cache pipenv virtualenv
+        uses: actions/cache@v4
         with:
-          path: ~/.local/share/virtualenvs
-          key: deps-python-${{ hashFiles('**/Pipfile.lock') }}
-
-      - name: RUN TESTS
-        run: pipenv run test
+          path: |
+            ~/.local/share/virtualenvs
+            ~/.cache/pip
+          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
+      - name: Install the dependencies
+        run: |
+          cd starter/backend
+          pipenv install --dev
+      - name: Run linter
+        run: |
+          cd starter/backend
+          pipenv run lint
         continue-on-error: false
-
-  build:
-    name: Build
+      - name: Run hadolint for dockerile
+        run: |
+          sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && sudo chmod +x /usr/local/bin/hadolint
+          /usr/local/bin/hadolint starter/backend/Dockerfile
+        continue-on-error: false
+  backend-cd-test:
+    name: backend-cd-test
     runs-on: ubuntu-latest
-    needs: [lint,test]
-    defaults:
-      run:
-        working-directory: starter/backend
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
+      - name: Install pipenv
+        run: |
+          python -m pip install --upgrade pip
+          pip install pipenv
+      - name: Cache pipenv virtualenv
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.local/share/virtualenvs
+            ~/.cache/pip
+          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
+      - name: Install the dependencies
+        run: |
+          cd starter/backend
+          pipenv install --dev
+      - name: Run tests
+        run: |
+          cd starter/backend
+          pipenv install
+          pipenv run test
+  backend-cd-build:
+    name: backend-cd-build
+    needs:
+      - backend-cd-test
+      - backend-cd-lint
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Configure AWS
-        uses: aws-actions/configure-aws-credentials@v3
+        uses: actions/checkout@v4
+      - name: Set up Python 3.10
+        uses: actions/setup-python@v5
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
-          aws-region: ${{ secrets.AWS_REGION }}
-      
+          python-version: '3.10'
+      - name: Install pipenv
+        run: |
+          python -m pip install --upgrade pip
+          pip install pipenv
+      - name: Cache pipenv virtualenv
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.local/share/virtualenvs
+            ~/.cache/pip
+          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
+      - name: Install the dependencies
+        run: |
+          cd starter/backend
+          pipenv install --dev
+      - name: Set up AWS CLI
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ vars.AWS_REGION }}
       - name: Login to ECR
         id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
-
-      - name: Build and Push the Docker Image to ECR
+        uses: aws-actions/amazon-ecr-login@v2
+      - name: Build, tag, and push docker image to Amazon ECR
         env:
           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          REPOSITORY: backend
-          IMAGE_TAG: ${{ github.sha }}  
-        run:  |
-          echo "Building Docker image for backend..."
-          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
-          echo "Pushing the backend Docker image to ECR repo..."
-          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
-
-      - name: Setup Kubeconfig
+          IMAGE_NAME: backend
         run: |
-          echo "Configuring kubectl for EKS..."
-          aws eks update-kubeconfig --name cluster --region ${{ secrets.AWS_REGION }}
-          kubectl get svc
-          kubectl config view
-
-      - name: Run init.sh
-        run:  |
-          chmod +x init.sh 
-          ./init.sh || true
-          kubectl config view
-        working-directory: setup
-
-      - name: Deploy to Kubernetes
+          echo Building docker image for backend ..
+          docker build -t $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7} starter/backend/.
+          echo Pushing the backend docker image to ECR repo
+          docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}
+  backend-cd-deploy:
+    name: backend-cd-deploy
+    runs-on: ubuntu-latest
+    needs:
+      - backend-cd-build
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
+      - name: Setup kubectl
+        uses: azure/setup-kubectl@v3
+        with:
+          version: v1.29.0
+      - name: Set up AWS CLI
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ vars.AWS_REGION }}
+      - name: Login to ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+      - name: Generate Kubeconfig
+        run: |
+          aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{vars.CLUSTER_NAME}}
+      - name: Setup Kustomize
+        uses: imranismail/setup-kustomize@v2
+      - name: Deploy backend App
         env:
           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-        run: |
-          cd k8s
-          kustomize edit set image backend=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend:latest
-          echo "Deploying to Kubernetes..."
+          IMAGE_NAME: backend
+          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
+          aws_default_region: ${{ vars.AWS_REGION }}
+        run: | 
+          cd starter/backend/k8s
+          kustomize edit set image backend=$REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}
           kustomize build | kubectl apply -f -
-          kubectl get svc -A
+      - name: Set REACT_APP_MOVIE_API_URL Repository Variable
+        env:
+          GH_TOKEN: ${{ secrets.TOKEN_GITHUB_X }}
+        run: |
+          kubectl rollout status deployment/backend
+          if [ $? -eq 0 ]; then
+            echo "Rollout successful. Fetching the external IP or DNS name..."
+            # Get the external IP or DNS name of the service
+            EXTERNAL_IP=$(kubectl get svc backend -o json | jq -r '.status.loadBalancer.ingress[0].hostname')
+            # Check if the EXTERNAL_IP is not empty
+            echo "Check if the EXTERNAL_IP is not empty"
+              if [ -n "$EXTERNAL_IP" ]; then
+                echo "External IP or DNS name: $EXTERNAL_IP"
+                gh secret set REACT_APP_MOVIE_API_URL --body "$EXTERNAL_IP"
+              else
+                  echo "External IP or DNS name not available yet."
+              fi
+          else
+            echo "Rollout failed."
+          fi
